### ISSUE TITLE
Is there way to inject overlay to context of GlobalKey<NavigatorState>?

### ISSUE THREAD

**Issue by nero-angela** [sososdk/flash#25]
Thanks you for making a good package.

In the previous version, after injecting the context of `GlobalKey<NavigatorState>` once, it was using flash well as if there was no dependency on the context. However, in the latest version, this method cannot be used because it has been updated so that the flash can be displayed only by using the context with overlay.

https://github.com/sososdk/flash/issues/21 is very similar to my situation. I wonder is it possible to inject an overlay into context of `GlobalKey<NavigatorState>`? if it possible, can you write some sample code?

**Comment by sososdk** [comment]
Hi @nero-angela 
When the parameter 'persistent' is true, `flash` uses the root overlay, it is get from `Navigator.of(context, rootNavigator: true).overlay`. You can injecting the context of `GlobalKey<NavigatorState>` and show flash freely.

Sample:

```dart
GlobalKey<NavigatorState> key;

showToast() {
  return showFlash(
    context: key.currentContext,
    persistent: true, // default
    builder: (context, controller) {
      return Flash(...);
    }
  );
}
```

Otherwise, when the parameter 'persistent' is false, `flash` uses the closest overlay and can not the root overlay. You need wrap the context with `Overlay`.

Sample:

```dart
Navigator.of(context).push(MaterialPageRoute(builder: (context) {
  return Overlay(
    initialEntries: [
      OverlayEntry(builder: (context) {
        return FlashPage();
      }),
    ],
  );
}

class FlashPage extends StatelessWidget {
  ......

  showFlash(
    context: context,
    persistent: false,
    builder: (context, controller) {
        return Flash(...);
     }
  );

  ......
}
```

**Comment by Ruzo** [comment]
It would have been great to find this thread in Discussions instead.
